# Generated by Django 4.2.20 on 2025-04-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hand_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
